[IV-21-22] Objetivo 2
Slowmybrosh/DietApp pull request #19
Opened 2021-10-30 13:19 UTC by migueorg

- Se ha creado la unidad mínima que compone una dieta, esta es, una clase cuyos atributos son los valores nutricionales que se deben ingerir por día. Siendo cada instancia del objeto un día de la semana. Con esto closes #17 y closes #16  Más detalles en 620bc65
- Se ha planteado brevemente como podría usarse este enfoque para llevar un registro semanal de los valores nutricionales recomendados basándose en los días anteriores. Con esto closes #18 Más detalles en a2a2e4d 
- Se ha añadido el archivo iv.yaml 52554b8
- Se ha actualizado el .gitignore para que no añada basura de Finder 9d0779d 
- Se ha determinado el lenguaje a utilizar. 52554b8

Estos cambios también avanzarían parte del #11 y se completaría [M0]

2021-11-02 16:59 UTC, Slowmybrosh commented
Me gusta la solución para #16, nada más comentar que el fichero 'IV.yaml' tiene que acabar en un salto de línea para que pase los tests

2021-11-03 11:51 UTC, migueorg commented
Cierto, disculpa, se me olvidó el salto de línea, ya he visto que lo has corregido tú directamente en 7cf4364.

2021-11-03 17:06 UTC, Slowmybrosh commented
Pues con esto, ya queda listo para revisión. @JJ

2021-11-05 10:09 UTC, JJ requested changes
Deberíais pegarle un pequeño repaso a esto, sobre todo justificar bien los cambios en base a las HUs.

2021-11-05 10:09 UTC, JJ commented on src/DietaSemanal.ts
> +    private valores_lunes: ValorNutricional;
¿lunes?

2021-11-05 10:09 UTC, JJ commented on src/DietaSemanal.ts
> +    valores_martes = new ValorNutricional(); //Ejemplo de como podría almacenar más días a parte del anterior en casi de que se quisiese
¿Esto es una variable de clase?

2021-11-05 10:09 UTC, JJ commented on src/DietaSemanal.ts
> +    private list: ValorNutricional[];
No llames list a una lista

2021-11-05 10:09 UTC, JJ commented on src/DietaSemanal.ts
> +        return this.list[0];
No entiendo muy bien que hace esto. Deberíais darle un repaso a TypeScript y también a lo que queréis hacer.

2021-11-12 13:07 UTC, migueorg commented
- Tras las correcciones de @JJ me he dado de que estaba abarcando demasiado y he decido dar un paso atrás para enfocarme solo en la entidad mínima como se especifica en #17 
- Además también he corregido la forma de hacer los commits siguiendo las indicaciones de clase. 
- De paso he revisado una errata de sintaxis de Markdown en el README  48eb1ba
- Con el commit 898343b arreglo un fallo que he tenido a la hora de hacer el commit 763d1f1 intentando referenciar al issue.

Tras esto, por mi parte ya estaría listo para revisión por @Slowmybrosh.

2021-11-13 12:13 UTC, Slowmybrosh commented
@JJ listo para revisión

2021-11-13 18:34 UTC, JJ approved these changes
Hay mejores formas de hacer lo que quieres hacer, pero lo importante es el proceso y finalmente lo has seguido con precisión.

2021-11-14 09:54 UTC, merged