Objetivo 3
Slowmybrosh/DietApp pull request #20
Opened 2021-11-14 10:42 UTC by Slowmybrosh

2021-11-14 23:35 UTC, Slowmybrosh commented
@JJ Listo para revisión

2021-11-17 10:59 UTC, JJ requested changes
Aparte de lo que te indico, esto es una parte del proyecto como otra cualquiera. Si tienes que cambiar código, tienes que hacer un issue que referencie una HU, y por supuesto tiene que ser parte de un milestone.

2021-11-17 10:59 UTC, JJ commented on src/ValorNutricional.ts
> +        if( kilojulios !== undefined && kilocalorias !== undefined && grasa !== undefined && proteinas !== undefined && fibra !== undefined && sal !== undefined && azucar !== undefined && sodio !== u
¿Seguro que no puedes hacer un bucle aquí?

2021-11-17 10:59 UTC, JJ commented on src/ValorNutricional.ts
> +            this.kilocalorias = kilocalorias;
Este se puede calcular del anterior (o al revés).

2021-11-17 10:59 UTC, JJ commented on src/ValorNutricional.ts
> +            throw new Error('Parametros del constructor invalidos');
Por favor, cread excepciones específicas para vuestro problema, ya os lo dije.

2021-11-17 16:32 UTC, Slowmybrosh commented
@JJ He mirado las reviews que se hicieron sobre los archivos de código, quiero aclarar que solo los he tocado porque en la solución del objetivo 2 que subió mi compañero no compilaba debido a un error en el propio código que solventé de cara a este nuevo objetivo.

He subido una nueva versión del fichero con los cambios propuestos que me comentaste

2021-11-19 07:43 UTC, Slowmybrosh commented
@JJ Listo para revision

2021-11-19 09:12 UTC, JJ reviewed
El problema principal es que no has desarrollado contra ningún issue; ni siquiera el objetivo principal, que era añadir el task runner. Siempre hay que trabajar contra issues y para acercarse a un producto mínimamente viable (que tampoco has puesto en este caso)

2021-11-19 09:12 UTC, JJ commented on src/ValorNutricional.ts
> +                throw new Error('Las proteinas no pueden estar vacías');
Una vez más, deberías crear una excepción específica como hablamos ayer en clase.

2021-11-19 09:12 UTC, JJ commented on src/ValorNutricional.ts
> +            if(hierro !== undefined){
¿De veras vas a usar todo esto del tirón en la lógica de negocio? ¿No habrá alguno que no uses inicialmente?

2021-11-19 09:12 UTC, JJ commented on src/ValorNutricional.ts
> +                throw new Error('El fosforo no puede estar vacío');
Del resto no sé, ¿pero no habrá cosas que no tengan fósforo? ¿No tiene ninguno de ellos un valor por omisión razonable?

2021-11-19 10:22 UTC, Slowmybrosh commented
@JJ Listo para revisión

2021-11-19 10:25 UTC, Slowmybrosh commented
@JJ Había un error tipográfico, ahora si que esta listo para revisión

2021-11-19 11:23 UTC, JJ approved these changes
:ok_hand: , me vale, pero por favor no pongas commits como 5520834 que además de hacerlo mal (hay que poner closes delante de cada uno), va en contra de todas las buenas prácticas al respecto.

2021-11-19 11:47 UTC, merged