[IV-21-22] Objetivo 4
Slowmybrosh/DietApp pull request #27
Opened 2021-11-21 19:07 UTC by Slowmybrosh

2021-11-21 19:26 UTC, Slowmybrosh commented
@JJ Listo para revisión

2021-11-21 19:39 UTC, JJ requested changes
El problema principal es que ninguno de los cambios que has hecho se corresponde con ningún issue ni por tanto con una HU. El resto de los comentarios te agradecería que los tuvieras en cuenta.

2021-11-21 19:39 UTC, JJ commented on docs/tools.md
> +Existen bastantes frameworks para ejecutar los test sobre el proyecto que se está desarrollando, investigando un poco podemos ver algunos como: Jest, Mocha e Intern.
¿Intern? ¿Podías enlazar?

2021-11-21 19:39 UTC, JJ commented on docs/tools.md
> +Cada framework tiene sus propias ventajas y desventajas, pero usaremos Jest que se ajusta a las necesidades del proyecto, ya que este no va a ser muy grande.
No dices cuales son esas necesidades.

2021-11-21 21:14 UTC, Slowmybrosh commented
He trabajado sobre la clase 'ValorNutricional' que correspondería con HU00, pero la cerró Migue al acabar su objetivo. ¿La vuelvo a abrir?

2021-11-22 10:55 UTC, JJ commented
> He trabajado sobre la clase 'ValorNutricional' que correspondería con HU00, pero la cerró Migue al acabar su objetivo. ¿La vuelvo a abrir?

Puedes hacer lo que estimes conveniente, pero mi opinión es que antes de reabrir un issue crearía otro nuevo con la parte del problema que quede.

2021-11-22 16:12 UTC, Slowmybrosh commented
@JJ Listo para revisión

2021-11-22 17:21 UTC, JJ commented
> He trabajado sobre la clase 'ValorNutricional' que correspondería con HU00, pero la cerró Migue al acabar su objetivo. ¿La vuelvo a abrir?

En este objetivo tienes que testear la lógica de negocio, que por tanto tendría que estar programada más allá de lo que hicieran en el objetivo 2. Ese es el problema principal que te mencionaba más arriba. Lo de los enlaces era secundario.

2021-11-23 12:19 UTC, Slowmybrosh commented
Se ha implementado una clase 'Dieta' que será la que posteriormente contendrá los diferentes Valores nutricionales para la semana. 

Además se ha avanzado en la lógica de negocio calculando las calorías recomendadas que tendrán que consumirse diariamente siguiendo las especificaciones de #29 y trabajando sobre la historia de usuario #28. También se han añadido los test correspondientes para esta nueva clase y su gestión de errores.

2021-11-23 12:19 UTC, Slowmybrosh commented
@JJ listo para revisión

2021-11-23 13:04 UTC, JJ commented
> El problema principal es que ninguno de los cambios que has hecho se corresponde con ningún issue ni por tanto con una HU. El resto de los comentarios te agradecería que los tuvieras en cuenta.

Sigues teniendo el mismo problema. Sólo hay un commit que se refiera a un issue, y el issue ni siquiera representa un problema. Si no desarrollas contra issues, puedes poner cualquier cosa; va a dar igual.

2021-11-23 15:32 UTC, Slowmybrosh commented
Cree #28 porque mi intención era también mostrar al usuario las calorías recomendadas para sus medidas y el estilo de vida que lleva, no solo la dieta.

Pero si no sirve esa HU, todo lo que he hecho para este objetivo se puede asignar a #11 ya que es un paso intermedio para formar la dieta. Avanzando así en M1

2021-11-23 15:40 UTC, JJ commented
> Cree #28 porque mi intención era también mostrar al usuario las calorías recomendadas para sus medidas y el estilo de vida que lleva, no solo la dieta.

Tú lo has dicho, es *tu* intención. Eso es un issue. Una HU es lo que el *usuario* quiere. No lo que tú quieres enseñarle al usuario.
> 
> Pero si no sirve esa HU, todo lo que he hecho para este objetivo se puede asignar a #11 ya que es un paso intermedio para formar la dieta. Avanzando así en M1

No he dicho que no sirva. He dicho que no es una HU.

2021-11-23 16:41 UTC, Slowmybrosh commented
He cambiado #28 para dejarlo como un issue, con la subida anterior del código iría un commit para cerrar este issue y no sé si tengo que ponerlo explicitamente ahora.

Por otra parte, se ha trabajado sobre #11, aunque se haya implementado solo una parte de la lógica de negocio.

2021-11-23 16:41 UTC, Slowmybrosh commented
@JJ Listo para revisión

2021-11-24 16:33 UTC, Slowmybrosh commented
He añadido los commits que cierran las issues que han sido completadas, también se ha completado #28 pero no sabía si hacer en un mismo commit dos cierres de issue

2021-11-24 16:34 UTC, Slowmybrosh commented
@JJ Listo para revisión

2021-11-26 08:12 UTC, JJ approved these changes
:+1:  porque está bastante currado, sobre todo los tests. Pero por favor, sigue a partir de ahora las buenas prácticas en issues y mensajes de commit. Los issues son problemas, se cierran con un commit cuyo mensaje que explique cómo se ha resuelto el problema, no con un closes no sé qué. Hazlo así a partir de ahora.
El resto de los comentarios, te agradecería que lo hicieras antes del siguiente objetivo.

2021-11-26 08:12 UTC, JJ commented on src/dieta.ts
> +export class Dieta{
Para evitar esto (no hay espacio antes del {) te aconsejo que añadas un linter en el objetivo 6.

2021-11-26 08:12 UTC, JJ commented on src/dieta.ts
> +    private calcularRecomendadas(edad:number, altura:number, peso:number,sexo:string, actividad:Tipo_actividad, objetivo:Tipo_dieta):number{
Aquí no usas la edad. ¿La vas a usar en algún lugar?

2021-11-26 08:12 UTC, JJ commented on src/dieta.ts
> +            TMB = (10*peso)+(6.25*altura)-(5*edad)+5;
constantes repetidas piden que les pongas un nombre y las pongas en algún lado.

2021-11-26 08:12 UTC, JJ commented on src/dieta.ts
> +        if(actividad == Tipo_actividad.SEDENTARIO){
Cuando hay ifs en cascada te están pidiendo a gritos un diccionario para que sea constante en vez de O(n)

2021-11-27 09:15 UTC, merged