[IV-21-22] Objetivo 6
Slowmybrosh/DietApp pull request #38
Opened 2021-11-30 17:12 UTC by Slowmybrosh

Se han elegido dos herramientas de integración continua 'Travis CI' y 'Circle CI' que se han configurado correctamente de acuerdo a lo especificado en (#37 )

Ambas herramientas han sido probadas y se han pasado los 'cheks' creados para este objetivo.

2021-11-30 17:20 UTC, Slowmybrosh commented
@JJ Listo para la revisión.

2021-12-01 09:02 UTC, JJ requested changes
Por favor, muestra un poco más qué has buscado para quedarte con eso.

2021-12-01 15:03 UTC, Slowmybrosh commented on .travis.yml
> +  - lts/*
La versión 14 es la versión más antigua en la que se puede usar Jest, y luego puse la última versión con 'node' que debería ser la 17 y la versión estable más reciente. Ya que la versión 17 no es estable, o eso leí

2021-12-01 16:40 UTC, Slowmybrosh commented
@JJ Listo para revisión.

2021-12-03 07:45 UTC, JJ approved these changes
Voy a aprobarlo, pero de veras que tendríais que intentar buscar un poco más que las dos herramientas que se han mencionado en clase. Ni siquiera pones GitHub Actions, y la estás usando para los push.

2021-12-03 07:45 UTC, JJ commented on docs/tools.md
> +Se han elegido Travis CI y CircleCI como sistemas de integración continua a usar en el proyecto, pero eso no significa que sean los unicos que existan.
typo

2021-12-03 07:45 UTC, JJ commented on docs/tools.md
> +De las mayores ventajas de Jenkins es que es gratuito y cuenta con una gran comunidad sobre la que se apoya esta comunidad, ya que es de código abierto.
No me creo lo de Jenkins. Tendrías que instalártelo tú.

2021-12-03 07:45 UTC, JJ commented on docs/tools.md
> +Por otra parte se contempló la idea de utilizar TeamCity, que también ofrece una suscripción gratuita sin limitaciones en el número de builds que hacer y que cuenta con construcciones simultaneas en
Esto es un poco voy a ponerlo porque me lo ha pedido, pero realmente ni se me pasó por la cabeza usarlo, ni lo probé, ni nada. Also, typo.

2021-12-03 07:48 UTC, merged