[IV-21-22] Objetivo 7
Slowmybrosh/DietApp pull request #43
Opened 2021-12-08 23:30 UTC by Slowmybrosh

Se ha creado una clase "Configuración" (#40), que permite automatizar y desplegar una aplicación distribuida. Para ello se ha usado Etcd3, de acuerdo a lo especificado en la documentación.

Adicionalmente, se ha añadido un "logger" (#39) que permite llevar registros de lo que va ocurriendo en dicha aplicación. 

A lo largo del desarrollo del objetivo han surgido problemas que se han solventado:
- Problema de actualización de dependencias en dockerhub (#41)
- Problema en la ejecución de los test (#42)

2021-12-09 18:17 UTC, JJ requested changes
Supongo que no ha pasado los tests todavía, mientras lo haces dale una vueltecilla.

2021-12-09 18:17 UTC, JJ commented on Dockerfile
> +RUN chown -R node . && chmod 777 -R .
Uf, qué poco me gusta esto...

2021-12-09 18:17 UTC, JJ commented on docs/tools.md
> +Adicionalmente, se intentó integrar roarr que es un logger muy completo, parecido a Winston y con mucho potencial, pero no fui capaz de configurarlo completamente para mandar los registros a un fiche
Pero pon enlaces, hombre...

2021-12-09 18:17 UTC, JJ commented on docs/tools.md
> +
Sigues sin poner los criterios para seleccionar antes de listar lo que hay y lo que has elegido.

2021-12-09 18:27 UTC, Slowmybrosh commented on Dockerfile
> +RUN chown -R node . && chmod 777 -R .
Esto es de una versión anterior (cuando creaba los logs en la misma carpeta del proyecto) que se me olvidó volverlo a poner con valor '755'

2021-12-09 18:29 UTC, JJ commented on Dockerfile
> +RUN chown -R node . && chmod 777 -R .
Pero es que da igual. En la carpeta que montes los directorios exteriores va a dar igual los permisos que le pongas. Y no es buena práctica dar más permisos que los estrictamente necesarios.

2021-12-10 08:24 UTC, Slowmybrosh commented
* [ ] ¿Se han registrado todos los eventos relevantes en la aplicación, es decir, se
  han añadido comandos para registrarlos en todos ellos?
* [ ] ¿Se han seguido buenas prácticas en el uso de configuración remota?
* [ ] ¿Se han explicado correctamente las decisiones técnicas que se han tomado
  sobre las bibliotecas usadas?
* [ ] ¿Te has asegurado de que el fichero `.env` no se pueda añadir
accidentalente al repositorio?

2021-12-10 10:34 UTC, JJ approved these changes
El objetivo está superado, pero deberías darle una vuelta a lo que se ha comentado, sobre todo la justificación.

2021-12-10 10:34 UTC, JJ commented on .circleci/config.yml
> +      - run: docker run -e LOG_DIR=$LOG_DIR -e LOG_FOLDER=$LOG_FOLDER -t -v `pwd`:/app/test slowmybrosh/dietapp
Estas cosas os agradecería que las documentárais. Si no para mi (que me lo has contado), para mi del futuro (que no se acordará)

2021-12-10 10:34 UTC, JJ commented on docs/tools.md
> +Otro logger que se probó fue [loglevel](https://www.npmjs.com/package/loglevel). Este es un logger minimalista con multitud de niveles, desde los niveles más bajos (Trace y Debug) hasta los más altos
Tienes que poner los criterios de antemano, repito.

2021-12-10 10:34 UTC, JJ commented on docs/tools.md
> +Adicionalmente, se intentó integrar [roarr](https://www.npmjs.com/package/roarr) que es un logger muy completo, parecido a Winston y con mucho potencial, pero no fui capaz de configurarlo completamen
¿Qué configuración necesita entonces?

2021-12-10 10:34 UTC, JJ commented on src/ValorNutricional.ts
> +const child = logger.child({a:'ValorNutricional'})
Esto no debería ser una variable global de módulo, sino un objeto que inyectas en la clase... Pero no en la clase que ya tienes (closed for modification) sino en otra clase (open for extension)

2021-12-10 10:34 UTC, JJ commented on src/ValorNutricional.ts
> +                child.error("Valor kilocalorias incorrecto");
Este tipo de cosas, por ejemplo, deberían capturarse a un nivel superior, que sería donde se loguearía. No debes modificar las clases que ya tengas.

2021-12-10 10:34 UTC, JJ commented on src/ValorNutricional.ts
> +            child.info("Creado objeto de la clase ValorNutricional")
También en otra clase de nivel superior. Siempre crear nuevos niveles de abstracción.

2021-12-10 10:34 UTC, JJ commented on src/logger.ts
> +if(!fs.existsSync(Configuration.getLog_folder())){
Deberías capturar el error aquí.

2021-12-10 10:34 UTC, JJ commented on src/logger.ts
> +const dest = pino.destination(Configuration.getLog_folder()+Configuration.getLog_dir())
¿Folder y dir no son lo mismo?

2021-12-17 10:51 UTC, merged